import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/ui/header";
import PageTransition from "../components/ui/pageTransition.jsx";
import StairTransition from "../components/ui/stairTransition.jsx";

const jetbrainsMono = JetBrains_Mono({ 
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-jetbrainsMono'
 });

export const metadata = {
  title: "Andy Mai - Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>

      </body>
    </html>
  );
}
